Добавляет базовую стилизацию всех страниц
htmlacademy-htmlcss/2051087-sedona-34 pull request #4
Opened 2022-05-31 21:04 UTC by Woodman209

2022-05-31 21:08 UTC, Woodman209 commented
У меня не подключаются звездочки, хотя вроде бы делаю все правильно

2022-06-01 16:37 UTC, Safyann requested changes
посмотри пути для изображений, лучше использовать относительные

2022-06-01 16:37 UTC, Safyann commented on styles/styles.css
> +    background-image: url('/images/header/search.svg');
лучше использовать относительные пути

2022-06-01 16:37 UTC, Safyann commented on styles/styles.css
> +    background-image: url('/images/header/favorite.svg');
лучше использовать относительные пути

2022-06-01 16:37 UTC, Safyann commented on styles/styles.css
> +    background-image: url('/images/catalog/catalog-background.jpg');
лучше использовать относительные пути

2022-06-01 16:37 UTC, Safyann commented on styles/styles.css
> +    background-image: url('/images/catalog/star.svg');
лучше использовать относительные пути

2022-06-02 02:35 UTC, merged